version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=loadtesting
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    restart: unless-stopped

    jmeter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jmeter
    volumes:
      - ./jmeter/test-plans:/test-plans
      - ./results:/results
    depends_on:
      - influxdb
    environment:
      - TEST_PLAN=/test-plans/basic_test.jmx
      - RESULTS_FILE=/results/results.csv
